// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWiY6MMpfT-wQbFcY1ykUr8IJkf0b82sA',
    appId: '1:333688532917:web:029c05a58be724e07db3fc',
    messagingSenderId: '333688532917',
    projectId: 'blockradar-pulse',
    authDomain: 'blockradar-pulse.firebaseapp.com',
    storageBucket: 'blockradar-pulse.firebasestorage.app',
    measurementId: 'G-T4YTF6NETQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv0W5hsZVH_g5WvrZ0EwTjwdo-1Fougis',
    appId: '1:333688532917:android:dc9d8c44fa6d04937db3fc',
    messagingSenderId: '333688532917',
    projectId: 'blockradar-pulse',
    storageBucket: 'blockradar-pulse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY6q80NRIRAeCI1w9bDq9ig_rfriQN7wM',
    appId: '1:333688532917:ios:bfd089bc945de4257db3fc',
    messagingSenderId: '333688532917',
    projectId: 'blockradar-pulse',
    storageBucket: 'blockradar-pulse.firebasestorage.app',
    iosBundleId: 'com.example.blockradarPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY6q80NRIRAeCI1w9bDq9ig_rfriQN7wM',
    appId: '1:333688532917:ios:bfd089bc945de4257db3fc',
    messagingSenderId: '333688532917',
    projectId: 'blockradar-pulse',
    storageBucket: 'blockradar-pulse.firebasestorage.app',
    iosBundleId: 'com.example.blockradarPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWiY6MMpfT-wQbFcY1ykUr8IJkf0b82sA',
    appId: '1:333688532917:web:747afa13575c05037db3fc',
    messagingSenderId: '333688532917',
    projectId: 'blockradar-pulse',
    authDomain: 'blockradar-pulse.firebaseapp.com',
    storageBucket: 'blockradar-pulse.firebasestorage.app',
    measurementId: 'G-KRCDE3544G',
  );
}
